### ISSUE TITLE
Prevent creation when tenant is missing

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-management-server#3]
Prevent creation of tenantFQDNs and tenantOAuths when tenant is missing.

**Comment by N7Remus** [comment]
Tenant id is missing only if the user who is creating not in a tenant (by default only the superadmin).
I am guessing that by design tenant admins should set up their own fqdn-s and auths.
Witch is impossible if no auth is configured.
I updated it for FQDN, as for OAuths it is already limiting this.
